baseURL = "http://www.paisaiq.netlify.com/"
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "3"
summaryLength = "15"
theme = ""
title = "Paisa IQ"
[markup.goldmark.renderer]
unsafe = true
[[menu.footer_left]]
URL = "#"
name = "About Us"
[[menu.footer_left]]
URL = "#"
name = "Quick Start"
[[menu.footer_left]]
URL = "pricing"
name = "Pricing"
[[menu.footer_middle]]
URL = "pricing"
name = "Pricing"
[[menu.footer_middle]]
URL = "#"
name = "Platform"
[[menu.footer_middle]]
URL = "#"
name = "Features"
[[menu.footer_right]]
URL = "privacy-policy"
name = "Privacy Policy"
[[menu.footer_right]]
URL = "terms-conditions"
name = "Terms & Conditions"
[[menu.footer_right]]
URL = "faq"
name = "FAQ"
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 1
[[menu.main]]
URL = "pricing"
name = "Subscription "
weight = 2
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 3
[[menu.main]]
URL = "faq"
name = "FAQs"
weight = 4
[params]
author = "Paisa IQ"
contact_form_action = "equityfundmaster@gmail.com"
copyright = "Developed By Mudit Garg "
description = "Your Paisa. Our Advice. "
footer_content = "The advice provided is general in nature. It does not constitute a recommendation to buy or sell any stock, and does not take account of your objectives, or your financial situation. We aim to bring you long-term focused analysis driven by fundamental data. Note that our analysis may not factor in the latest price-sensitive company announcements or qualitative material."
footer_menu_left = "Product"
footer_menu_middle = ""
footer_menu_right = ""
logo = "/images/piq-logo.png"
logo_width = "230px"
[params.navigation_button]
enable = true
label = "Get Started"
link = "contact"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[params.preloader]
enable = false
preloader = ""
[[params.social]]
icon = ""
link = ""
title = "Reddit"
[[params.social]]
icon = "ti-facebook"
link = "#"
title = "facebook"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
title = "twitter"
[[params.social]]
icon = "ti-linkedin"
link = "#"
title = "linkedin"
