baseURL = "http://www.paisaiq.netlify.com/"
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "3"
summaryLength = "15"
theme = ""
title = "Paisa IQ"
[markup.goldmark.renderer]
unsafe = true
[[menu.footer_left]]
URL = "#"
name = "About Us"
[[menu.footer_left]]
URL = "#"
name = "Quick Start"
[[menu.footer_left]]
URL = "pricing"
name = "Pricing"
[[menu.footer_middle]]
URL = "pricing"
name = "Pricing"
[[menu.footer_middle]]
URL = "#"
name = "Platform"
[[menu.footer_middle]]
URL = "#"
name = "Features"
[[menu.footer_right]]
URL = "privacy-policy"
name = "Privacy Policy"
[[menu.footer_right]]
URL = "terms-conditions"
name = "Terms & Conditions"
[[menu.footer_right]]
URL = "faq"
name = "FAQ"
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 1
[[menu.main]]
URL = "pricing"
name = "Pricing"
weight = 2
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 3
[[menu.main]]
URL = "faq"
name = "FAQ"
weight = 4
[params]
author = "Paisa IQ"
contact_form_action = "equityfundmaster@gmail.com"
copyright = "Developed By Mudit Garg "
description = "Your Paisa. Our Advice. "
footer_content = "The advice provided is general in nature. It does not constitute a recommendation to buy or sell any stock, and does not take account of your objectives, or your financial situation. We aim to bring you long-term focused analysis driven by fundamental data. Note that our analysis may not factor in the latest price-sensitive company announcements or qualitative material."
footer_menu_left = "Product"
footer_menu_middle = ""
footer_menu_right = ""
logo = "/images/piq-logo.png"
logo_width = "230px"
[params.navigation_button]
enable = true
label = "Get Started"
link = "contact"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[params.preloader]
enable = false
preloader = "// Variables $bar-color: #fff; $ball-color: #fff; $bg-color: #EA4961;  html {   height: 100%; } body {   height: 100%;   background: $bg-color;   display: flex;   align-items: center;   justify-content: center; }  .loader {      position: relative;   width: 75px;   height: 100px;      &__bar {     position: absolute;     bottom: 0;     width: 10px;     height: 50%;     background: $bar-color;     transform-origin: center bottom;     box-shadow: 1px 1px 0 rgba(0,0,0,.2);          @for $i from 1 through 5 {         &:nth-child(\#{$i}) {          left: ($i - 1) * 15px;          transform: scale(1,$i*.2);          animation: barUp\#{$i} 4s infinite;         }     }        }      &__ball {     position: absolute;     bottom: 10px;     left: 0;     width: 10px;     height: 10px;     background: $ball-color;     border-radius: 50%;     animation: ball 4s infinite;   } }  @keyframes ball {   0% {     transform: translate(0, 0);   }   5% {     transform: translate(8px, -14px);   }   10% {     transform: translate(15px, -10px)   }   17% {     transform: translate(23px, -24px)   }   20% {     transform: translate(30px, -20px)   }   27% {     transform: translate(38px, -34px)   }   30% {     transform: translate(45px, -30px)   }   37% {     transform: translate(53px, -44px)   }   40% {     transform: translate(60px, -40px)   }   50% {     transform: translate(60px, 0)   }   57% {     transform: translate(53px, -14px)   }   60% {     transform: translate(45px, -10px)   }   67% {     transform: translate(37px, -24px)   }   70% {     transform: translate(30px, -20px)   }   77% {     transform: translate(22px, -34px)   }   80% {     transform: translate(15px, -30px)   }   87% {     transform: translate(7px, -44px)   }   90% {     transform: translate(0, -40px)   }   100% {     transform: translate(0, 0);   } }  @keyframes barUp1 {    0% {     transform: scale(1, .2);   }   40%{     transform: scale(1, .2);   }   50% {     transform: scale(1, 1);   }   90% {     transform: scale(1,1);   }   100% {     transform: scale(1,.2);   } } @keyframes barUp2 {    0% {     transform: scale(1, .4);   }   40% {     transform: scale(1, .4);   }   50% {     transform: scale(1, .8);   }   90% {     transform: scale(1, .8);   }   100% {     transform: scale(1, .4);   } } @keyframes barUp3 {    0% {     transform: scale(1, .6);   }   100% {     transform: scale(1, .6);   } } @keyframes barUp4 {    0% {     transform: scale(1, .8);   }   40% {     transform: scale(1, .8);   }   50% {     transform: scale(1, .4);   }   90% {     transform: scale(1, .4);   }   100% {     transform: scale(1, .8);   } } @keyframes barUp5 {    0% {     transform: scale(1, 1);   }   40% {     transform: scale(1, 1);   }   50% {     transform: scale(1, .2);   }   90% {     transform: scale(1, .2);   }   100% {     transform: scale(1, 1);   } }"
[[params.social]]
icon = ""
link = ""
title = "Reddit"
[[params.social]]
icon = "ti-facebook"
link = "#"
title = "facebook"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
title = "twitter"
[[params.social]]
icon = "ti-linkedin"
link = "#"
title = "linkedin"
